version: '1.0'
steps:
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    image_name: duo2005duo/shadowsockslibev
    working_directory: ./
    dockerfile: docker/alpine/Dockerfile
shadowsocks:
  image: shadowsocks-libev
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=aes-256-cfb
    - PASSWORD=9MLSpPmNt
  restart: always
